const cfg=window.PKKM_CONFIG||{}; const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY); let me=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function init(){const {data:{session}}=await sb.auth.getSession(); if(session) await signed(session); else showLogin();}
async function signed(session){const {data:p}=await sb.from('profiles').select('*').eq('id',session.user.id).single(); me=p; $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#logout').classList.remove('hidden');load('dashboard')}
function showLogin(){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#logout').classList.add('hidden')}
$('#login').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)alert(error.message);else init()};$('#logout').onclick=async()=>{await sb.auth.signOut();showLogin()};
document.addEventListener('click',e=>{if(e.target.dataset.page)load(e.target.dataset.page)});
async function load(page){const c=$('#content');c.innerHTML='<div class="card">Memuat...</div>'; if(page==='dashboard')return dashboard(); if(page==='madrasah')return madrasah();if(page==='pengawas')return assignments();if(page==='indikator')return indicators();if(page==='bukti')return evidence();if(page==='verifikasi')return verification();if(page==='penilaian')return assessment();if(page==='laporan')return report();}
async function dashboard(){let [{count:md},{count:ind},{count:bt},{count:pn}]=await Promise.all([sb.from('madrasah').select('*',{count:'exact',head:true}),sb.from('indikator').select('*',{count:'exact',head:true}),sb.from('bukti').select('*',{count:'exact',head:true}),sb.from('penilaian').select('*',{count:'exact',head:true})]);$('#content').innerHTML=`<h2>Dashboard</h2><div class="grid"><div class="stat">Madrasah<b>${md||0}</b></div><div class="stat">Indikator<b>${ind||0}</b></div><div class="stat">Bukti Fisik<b>${bt||0}</b></div><div class="stat">Penilaian<b>${pn||0}</b></div></div><div class="card section"><h3>Alur PKKM</h3><p>Madrasah mengisi profil → mengunggah bukti → pengawas memverifikasi → pengawas memberi skor → sistem menghitung rekap → laporan dicetak.</p></div>`}
async function madrasah(){const {data}=await sb.from('madrasah').select('*').order('nama');let rows=(data||[]).map(x=>`<tr><td>${esc(x.nsm)}</td><td>${esc(x.nama)}</td><td>${esc(x.kepala_nama)}</td><td>${esc(x.kab_kota)}</td><td><button onclick='editMad(${JSON.stringify(x)})'>Edit</button></td></tr>`).join('');$('#content').innerHTML=`<h2>Data Madrasah</h2><div class="card section"><form id="mf" class="formgrid"><input name="id" type="hidden"><input name="nsm" placeholder="NSM"><input name="npsn" placeholder="NPSN"><input name="nama" placeholder="Nama Madrasah" required><input name="jenjang" value="MTs" placeholder="Jenjang"><input name="kab_kota" placeholder="Kabupaten/Kota"><input name="alamat" class="full" placeholder="Alamat"><input name="kepala_nama" placeholder="Nama Kepala Madrasah"><input name="kepala_nip" placeholder="NIP/NIY"><button class="full">Simpan Data Madrasah</button></form></div><div class="tablewrap"><table><tr><th>NSM</th><th>Madrasah</th><th>Kepala</th><th>Kab/Kota</th><th></th></tr>${rows}</table></div>`;$('#mf').onsubmit=saveMadrasah}
window.editMad=x=>{const f=$('#mf');Object.keys(x).forEach(k=>{if(f.elements[k])f.elements[k].value=x[k]||''});scrollTo(0,0)};
async function saveMadrasah(e){e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=o.id||undefined;let q=o.id?sb.from('madrasah').update(o).eq('id',o.id):sb.from('madrasah').insert({...o,user_id:me.id});const {error}=await q;if(error)alert(error.message);else madrasah()}
async function assignments(){const {data:ps}=await sb.from('pengawas').select('id,wilayah,profiles(nama)');const {data:ms}=await sb.from('madrasah').select('id,nama');const {data:a}=await sb.from('penugasan').select('*,pengawas(profiles(nama)),madrasah(nama)').order('tahun_ajaran',{ascending:false});$('#content').innerHTML=`<h2>Pengawas & Penugasan</h2><div class="card section"><form id="af" class="formgrid"><select name="pengawas_id">${(ps||[]).map(x=>`<option value="${x.id}">${esc(x.profiles?.nama||'')}</option>`).join('')}</select><select name="madrasah_id">${(ms||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('')}</select><input name="tahun_ajaran" placeholder="Tahun Ajaran 2026/2027" required><button>Tambah Penugasan</button></form></div><div class="tablewrap"><table><tr><th>Pengawas</th><th>Madrasah</th><th>Tahun Ajaran</th><th>Status</th></tr>${(a||[]).map(x=>`<tr><td>${esc(x.pengawas?.profiles?.nama)}</td><td>${esc(x.madrasah?.nama)}</td><td>${esc(x.tahun_ajaran)}</td><td>${esc(x.status)}</td></tr>`).join('')}</table></div>`;$('#af').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('penugasan').insert(Object.fromEntries(new FormData(e.target)));if(error)alert(error.message);else assignments()}}
async function indicators(){const {data}=await sb.from('indikator').select('*,komponen(nama)').order('urutan');$('#content').innerHTML=`<h2>Indikator PKKM</h2><div class="card section"><form id="if" class="formgrid"><input name="kode" placeholder="Kode" required><input name="komponen_id" placeholder="ID Komponen" required><input name="indikator" class="full" placeholder="Indikator kinerja" required><input name="deskripsi" class="full" placeholder="Deskripsi/bukti yang diharapkan"><input name="bobot" type="number" step="0.01" value="1"><input name="urutan" type="number" value="1"><button class="full">Tambah Indikator</button></form></div><div class="tablewrap"><table><tr><th>Kode</th><th>Komponen</th><th>Indikator</th><th>Bobot</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.kode)}</td><td>${esc(x.komponen?.nama)}</td><td>${esc(x.indikator)}<br><small>${esc(x.deskripsi)}</small></td><td>${x.bobot}</td></tr>`).join('')}</table></div>`;$('#if').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('indikator').insert(Object.fromEntries(new FormData(e.target)));if(error)alert(error.message);else indicators()}}
async function evidence(){const {data:m}=await sb.from('madrasah').select('id,nama');const {data:i}=await sb.from('indikator').select('id,kode,indikator').eq('aktif',true).order('urutan');$('#content').innerHTML=`<h2>Upload Bukti Fisik</h2><div class="card"><form id="bf" class="formgrid"><select name="madrasah_id" required>${(m||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('')}</select><select name="indikator_id" required>${(i||[]).map(x=>`<option value="${x.id}">${esc(x.kode)} - ${esc(x.indikator)}</option>`).join('')}</select><input name="keterangan" class="full" placeholder="Keterangan bukti"><input name="file" type="file" class="full" required><button class="full">Upload Bukti</button></form></div>`;$('#bf').onsubmit=uploadEvidence}
async function uploadEvidence(e){e.preventDefault();const f=e.target;const file=f.file.files[0];const path=`${f.madrasah_id.value}/${crypto.randomUUID()}-${file.name}`;const up=await sb.storage.from('bukti-pkkm').upload(path,file);if(up.error)return alert(up.error.message);const {data:u}=sb.storage.from('bukti-pkkm').getPublicUrl(path);const {error}=await sb.from('bukti').insert({madrasah_id:f.madrasah_id.value,indikator_id:f.indikator_id.value,nama_file:file.name,url:u.publicUrl,storage_path:path,keterangan:f.keterangan.value});if(error)alert(error.message);else{alert('Bukti berhasil diunggah');e.target.reset()}}
async function verification(){const {data}=await sb.from('bukti').select('*,madrasah(nama),indikator(kode,indikator)').order('uploaded_at',{ascending:false});$('#content').innerHTML=`<h2>Verifikasi Bukti Fisik</h2><div class="tablewrap"><table><tr><th>Madrasah</th><th>Indikator</th><th>Bukti</th><th>Status</th><th>Catatan</th><th>Aksi</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.madrasah?.nama)}</td><td>${esc(x.indikator?.kode)}<br>${esc(x.indikator?.indikator)}</td><td><a href="${esc(x.url)}" target="_blank">${esc(x.nama_file)}</a></td><td><span class="badge">${esc(x.status)}</span></td><td><input id="cat-${x.id}" value="${esc(x.catatan_verifikator)}"></td><td><button onclick="verify('${x.id}','valid')">Valid</button> <button onclick="verify('${x.id}','revisi')">Revisi</button></td></tr>`).join('')}</table></div>`}
window.verify=async(id,status)=>{const cat=$('#cat-'+id).value;const {error}=await sb.from('bukti').update({status,catatan_verifikator:cat}).eq('id',id);if(error)alert(error.message);else verification()}
async function assessment(){const {data:m}=await sb.from('madrasah').select('id,nama');const {data:i}=await sb.from('indikator').select('id,kode,indikator,bobot').eq('aktif',true).order('urutan');$('#content').innerHTML=`<h2>Penilaian Pengawas</h2><div class="card section"><select id="am">${(m||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('')}</select></div><div id="atable"></div>`;$('#am').onchange=()=>assessmentTable($('#am').value);if(m?.[0])assessmentTable(m[0].id)}
async function assessmentTable(mid){const {data:i}=await sb.from('indikator').select('id,kode,indikator,bobot').eq('aktif',true).order('urutan');const {data:p}=await sb.from('penilaian').select('*').eq('madrasah_id',mid);$('#atable').innerHTML=`<div class="tablewrap"><table><tr><th>Kode</th><th>Indikator</th><th>Bobot</th><th>Skor 1-4</th><th>Catatan</th><th></th></tr>${(i||[]).map(x=>{const v=(p||[]).find(z=>z.indikator_id===x.id);return `<tr><td>${x.kode}</td><td>${esc(x.indikator)}</td><td>${x.bobot}</td><td><select id="s-${x.id}"><option value="">-</option>${[1,2,3,4].map(n=>`<option ${v?.skor==n?'selected':''}>${n}</option>`).join('')}</select></td><td><input id="c-${x.id}" value="${esc(v?.catatan||'')}"></td><td><button onclick="saveScore('${mid}','${x.id}')">Simpan</button></td></tr>`}).join('')}</table></div>`}
window.saveScore=async(mid,iid)=>{const skor=Number($('#s-'+iid).value);if(!skor)return alert('Pilih skor');const {data:pg}=await sb.from('pengawas').select('id').eq('profile_id',me.id).single();const {error}=await sb.from('penilaian').upsert({madrasah_id:mid,indikator_id:iid,pengawas_id:pg?.id,skor,catatan:$('#c-'+iid).value,status:'draft',updated_at:new Date().toISOString()},{onConflict:'indikator_id,madrasah_id'});if(error)alert(error.message);else alert('Penilaian tersimpan')}
async function report(){const {data:m}=await sb.from('madrasah').select('id,nama');$('#content').innerHTML=`<h2>Laporan PKKM</h2><div class="card"><select id="rm">${(m||[]).map(x=>`<option value="${x.id}">${esc(x.nama)}</option>`).join('')}</select><button id="showr">Tampilkan Rekap</button></div><div id="rout"></div>`;$('#showr').onclick=()=>reportTable($('#rm').value);if(m?.[0])reportTable(m[0].id)}
async function reportTable(mid){const {data}=await sb.from('penilaian').select('skor,catatan,indikator(kode,indikator,bobot)').eq('madrasah_id',mid);let total=0,wb=0;let rows=(data||[]).map(x=>{const w=Number(x.indikator?.bobot||1);total+=Number(x.skor||0)*w;wb+=4*w;return `<tr><td>${x.indikator?.kode}</td><td>${esc(x.indikator?.indikator)}</td><td>${w}</td><td>${x.skor||'-'}</td><td>${esc(x.catatan)}</td></tr>`}).join('');const nilai=wb?(total/wb*100).toFixed(2):'0.00';$('#rout').innerHTML=`<div class="card"><h3>Nilai Akhir: ${nilai}</h3><button onclick="print()">Cetak / Simpan PDF</button></div><div class="tablewrap"><table><tr><th>Kode</th><th>Indikator</th><th>Bobot</th><th>Skor</th><th>Catatan</th></tr>${rows}</table></div>`}
init();
